package mocks

import io "io"
import mock "github.com/stretchr/testify/mock"
import resources "github.com/t11e/picaxe/resources"

// Resolver is an autogenerated mock type for the Resolver type
type Resolver struct {
	mock.Mock
}

// GetResource provides a mock function with given fields: identifier
func (_m *Resolver) GetResource(identifier string) (io.ReadSeeker, error) {
	ret := _m.Called(identifier)

	var r0 io.ReadSeeker
	if rf, ok := ret.Get(0).(func(string) io.ReadSeeker); ok {
		r0 = rf(identifier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadSeeker)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(identifier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

var _ resources.Resolver = (*Resolver)(nil)
