package mocks

import iiif "github.com/t11e/picaxe/iiif"
import io "io"
import mock "github.com/stretchr/testify/mock"
import resources "github.com/t11e/picaxe/resources"

// Processor is an autogenerated mock type for the Processor type
type Processor struct {
	mock.Mock
}

// Process provides a mock function with given fields: spec, resolver, w
func (_m *Processor) Process(spec string, resolver resources.Resolver, w io.Writer) error {
	ret := _m.Called(spec, resolver, w)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, resources.Resolver, io.Writer) error); ok {
		r0 = rf(spec, resolver, w)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

var _ iiif.Processor = (*Processor)(nil)
