package mocks

import iiif "github.com/t11e/picaxe/iiif"
import mock "github.com/stretchr/testify/mock"

// ProcessorFactory is an autogenerated mock type for the ProcessorFactory type
type ProcessorFactory struct {
	mock.Mock
}

// NewProcessor provides a mock function with given fields: params
func (_m *ProcessorFactory) NewProcessor(params iiif.Params) (iiif.Processor, error) {
	ret := _m.Called(params)

	var r0 iiif.Processor
	if rf, ok := ret.Get(0).(func(iiif.Params) iiif.Processor); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iiif.Processor)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(iiif.Params) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

var _ iiif.ProcessorFactory = (*ProcessorFactory)(nil)
