package mocks

import iiif "github.com/t11e/picaxe/iiif"
import io "io"
import mock "github.com/stretchr/testify/mock"

// Processor is an autogenerated mock type for the Processor type
type Processor struct {
	mock.Mock
}

// Process provides a mock function with given fields: _a0, _a1
func (_m *Processor) Process(_a0 io.ReadSeeker, _a1 io.Writer) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(io.ReadSeeker, io.Writer) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

var _ iiif.Processor = (*Processor)(nil)
